### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by CPythoner** [DavidLiRemini/FileOperation#1]
FileAttributes CC_file_win32::GetAttributes(std::string path)
{
	bool exist = Exists(path);
	_finddata_t fileInfo;
	if (exist)
	{
		intptr_t handle = _findfirst(path.c_str(), &fileInfo);
		if (handle == -1)
		{
			fprintf(stderr, "No matching Unknown attributes %s %d\n", __FUNCTION__, __LINE__);
			return FileAttributes::UNKNOWN;
		}
		auto value = (int)fileInfo.attrib;
		return (FileAttributes)value;
		_findclose(handle);
	}
	return FileAttributes::UNKNOWN;
}

此函数先返回然后再_findclose()，两行代码应该调换一下位置吧

**Comment by DavidLiRemini** [comment]
# 多谢指出错误
